version: '3.8'

services:
  restreamer:
    network_mode: host
    build: .
    container_name: video-restreamer
    ports:
      - "8000:8000"   # Exposes healthcheck and reload API
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
