openapi: 3.0.0
info:
  title: FMV Restreamer API
  version: 1.0.0
paths:
  /healthz:
    get:
      summary: Get health status of all streams
      responses:
        '200':
          description: JSON object with stream health
  /metrics:
    get:
      summary: Prometheus-compatible health metrics
      responses:
        '200':
          description: Prometheus text format
  /reload:
    post:
      summary: Reloads the stream config dynamically
      responses:
        '200':
          description: Config reloaded successfully
  /swagger:
    get:
      summary: Returns this Swagger YAML spec
      responses:
        '200':
          description: YAML content